#General configuration
general:
  scheduled_task:
    scheduler_interval:
    keep_alert_interval:

#ServiceNow configuration
service_now:
  enabled:
  module:
  instance_id:
  username:
  password:
  caller_id:
  state:
    in_progress:
    on_hold:
    hold_reason:

#MongoDB configuration
mongodb:
  hostname:
  port:
  username:
  password:
  database:
  collection:

#Slack configuration
slack:
  enabled:
  webhook_url:

#Zulip configuration
zulip:
  enabled:
  instance_url:
  email:
  api_key:
  channel: